/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventario.view;

import com.mycompany.inventario.OpenTable;
import com.mycompany.inventario.home;
import com.mycompany.inventario.Line;
import com.mycompany.inventario.Planilha;
import java.util.ArrayList;

/**
 *
 * @author range
 */
public class Busca extends javax.swing.JFrame {

    /**
     * Creates new form Busca
     */
    public home home;
    
    public Busca() {
        home = new home();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAdd = new javax.swing.JButton();
        textPN1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jTextResult = new java.awt.TextArea();
        listEscolha = new java.awt.List();
        jPanel2 = new javax.swing.JPanel();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnAdd.setText("Abrir arquivo");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        textPN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPN1ActionPerformed(evt);
            }
        });
        textPN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textPN1KeyReleased(evt);
            }
        });

        listEscolha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listEscolhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(listEscolha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextResult, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listEscolha, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAdd)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textPN1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textPN1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPN1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPN1KeyReleased
        // TODO add your handling code here:
        String PN = this.textPN1.getText();
        String res = "";
        
        for (int i = 0; i < this.home.numArquivos; i++) {
            boolean add = true;
            for (Line lin : this.home.arquivos.get(i).lines) {
                String s = lin.L.get("Manufacturer Part Number 1");
                if(s == null){
                    continue;
                } 
                if(s.equalsIgnoreCase(PN)){
                    //System.out.println(lin.L.get("Value")+ " ---> projeto: "+ this.home.arquivos.get(i).getName());
                    //System.out.println(this.listEscolha.getItemCount());
                    if(this.listEscolha.getItemCount() != 0){
                        for (int j = 0; j < (this.listEscolha.getItemCount()); j++) {
                            //System.out.println(this.listEscolha.getItem(j));
                            if(this.listEscolha.getItem(j).contains(lin.L.get("Value")+ " > "+lin.L.get("null")+ " > "+ this.home.arquivos.get(i).getName())){
                                add = false;
                                //System.out.println(this.listEscolha.getItem(j));
                            }
                        }
                    }
                    if(add){
                        this.placed = false;
                        this.listEscolha.add(lin.L.get("Value")+ " > "+lin.L.get("null")+ " > "+ this.home.arquivos.get(i).getName());
                        res += lin.L.get("Value")+ " > " + lin.L.get("null")+ " > " + this.home.arquivos.get(i).getName()+"\n";
                        this.jTextResult.setText(res);
                        break;
                    }  
                }
            }
        }
    }//GEN-LAST:event_textPN1KeyReleased

    private void textPN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPN1ActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        this.home.arquivos.put(home.numArquivos,OpenTable.openFile());
        this.list1.add(home.arquivos.get(home.numArquivos).getName());
        home.numArquivos ++;
    }//GEN-LAST:event_jBtnAddActionPerformed
    
    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        // TODO add your handling code here:
        //this.list1.getSelectedIndex();
        TableView tblView = new TableView();
        tblView.importBOM(this.home.arquivos.get(this.list1.getSelectedIndex()));
        tblView.setVisible(true);
        //ArrayList<Line> p = this.home.arquivos.get(this.list1.getSelectedIndex());
        //System.out.println(p.size());
        //System.out.println(p.get(1).name);
    }//GEN-LAST:event_list1MouseClicked

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    boolean placed;
    
    private void listEscolhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listEscolhaMouseClicked
        // TODO add your handling code here:
        String[] s = this.listEscolha.getItem(this.listEscolha.getSelectedIndex()).split(" > ", 3);
        for (String string : s) {
            System.out.println(string);  
        }
        for (int i = 0; i < this.home.numArquivos; i++) {
            if(this.home.arquivos.get(i).getName().equals(s[2]) && !this.placed){
                this.placed = true;
                this.home.arquivos.get(i).lines.get(Integer.parseInt(s[1])).L.put("Placed", "OK");
            }
        }
    }//GEN-LAST:event_listEscolhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextArea jTextResult;
    private java.awt.List list1;
    private java.awt.List listEscolha;
    private java.awt.TextField textPN1;
    // End of variables declaration//GEN-END:variables
}
