/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventario.view;

import com.mycompany.inventario.Line;
import com.mycompany.inventario.Planilha;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author range
 */
public class TableView extends javax.swing.JFrame {

    /**
     * Creates new form TableView
     */
    
    public Planilha P;
    
    public TableView() {
        initComponents();
    }
    
    public void importBOM(Planilha p){
        this.P =  p;
        boolean columnsName = false;
        DefaultTableModel tb = (DefaultTableModel)this.jTableBOM.getModel();
        String[] c = p.lines.get(0).L.keySet().toArray(String[]::new);
        if(tb.getColumnCount() < c.length){
                for (int j = tb.getColumnCount()+1; j < c.length; j++) {
                    tb.addColumn(c[j]);
                }
            }
        tb.setColumnIdentifiers(c);
        if(p.lines.get(0).L.containsKey("BLANK")){
            jTableBOM.removeColumn(jTableBOM.getColumn("BLANK"));
        }
        for (Line line : p.lines) {
            int i = 0;
            ArrayList<String> s = new ArrayList();
            for (Map.Entry<String, String> entry : line.L.entrySet()) {
                s.add(entry.getValue());
                /*if(columnsName){
                    c.add(entry.getKey());
                }*/
                //System.out.println(entry.getKey());
            }
            columnsName = false;
            /*if(tb.getColumnCount()<s.size()){
                for (int j = tb.getColumnCount()+1; j < s.size(); j++) {
                    tb.addColumn(c.get(j));
                }
            }else{
                for (int j = 0; j < c.size(); j++) {
                    tb.setColumnIdentifiers(c.toArray());
                }
            }*/
            tb.addRow(s.toArray());
        }
        
        //this.jTableBOM.add(p.lines.toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBOM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableBOM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableBOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBOM;
    // End of variables declaration//GEN-END:variables
}
